### ISSUE TITLE
Написать ReadMe для каждой своей задачи.

### ISSUE THREAD

**Issue by Kokorin86** [nko-nzhkc/nko#10]
Необходимо написать объяснение к каждой своей задаче.
@jisdtn объяснение решения задач про stripe.
@olkrpv вставка объяснений по переменным окружения.
@VitaliiCheremisov вставка объяснений по Cloudpayments.

**Comment by yan-gabala** [comment]
@yan-gabala описание работы работы пакета unisender на стадии MVP

**Comment by jisdtn** [comment]
готово

**Comment by yan-gabala** [comment]
На PR #16

**Comment by VitaliiCheremisov** [comment]
Готово
